# Alumno 
Pérez Gastón

## Ejercicio 01
Generar un array aleatorio de 100 elementos. Calcular la mediana correspondiente.

In [4]:
#Importamos librería NumPy

import numpy as np

In [13]:
def arrayRandom ():
    print("\nGenerador de arrays aleatorio compuestos por 100 elementos")
    print("==========================================================")

    arrayAleatorio = np.random.randint(100, size=(10,10))
    
    print("\nSu array Random es:")
    print("-------------------")
    print(arrayAleatorio)
    
    mediana = np.median(arrayAleatorio)
    print("\nLa mediana de su array es =",mediana)

print("Bienvenidx a este programa")
init = int(input("Para comenzar ingrese 1. Si no desea continuar, pulse 0: "))

if init == 1:
    arrayRandom()
else:
    print("La próxima será :)")

consulta = input("¿Quiere volver a utilizar el programa?: ")

while consulta == "si" or consulta == "SI" or consulta == "Si" or consulta == "sí" or consulta == "SÍ" or consulta == "Sí" or consulta == "sI" or consulta == "sÍ":
    arrayRandom()
    consulta = input("¿Quiere volver a utilizar el programa?: ")
else:
    print("¡Adiós Vaquerx!")

Bienvenidx a este programa
Para comenzar ingrese 1. Si no desea continuar, pulse 0: 1

Generador de arrays aleatorio compuestos por 100 elementos

Su array Random es:
-------------------
[[41 13 43 30 63 48 56 92 92 82]
 [26 89  1 64 65 39 75  3 25 92]
 [30  6 20 81 67 89 73 36 30 89]
 [74  3  1 46 73 70 42 47 58 36]
 [60  0 88 60 90 13 64  0 89 14]
 [22 91 21 53 81 70 72 66 53 26]
 [60 88 83 28 12 69 93 69  2 19]
 [93 57 49 47 14 16 40 79 74 21]
 [26 87 39  7  0 79 96 91 67 16]
 [83 53 36  9 40 17 29 75 94 53]]

La mediana de su array es = 53.0
¿Quiere volver a utilizar el programa?: Si

Generador de arrays aleatorio compuestos por 100 elementos

Su array Random es:
-------------------
[[59 42 21 83 74 52 61  0 81 72]
 [94 40 34 34 50 15 86 49 30 74]
 [ 0 67 18 98 68 79 80 72 75 79]
 [81 65 91 51 67 71 48 89 40 31]
 [ 3 20  0 31 27 40 79  2 11  9]
 [72 10 57 87 13 44 31  1 12 24]
 [21 71 10 74 79 31  1 23 56 78]
 [22 54 73 69 41 60 92 54 69 83]
 [11 49 73 70 84 41 19 93 32 95]
 [50  5

## Ejercicio 02
Recordar los ejercicios con funciones para cálculo de factorial y suma de serie de la Clase 02. Repetir ambos ejercicios, pero ahora utilizar las nuevas operaciones aprendidas con los ndarrays.

### Desafío 01
- Escribir una función para calcular el factorial de un número cualquiera.

In [4]:
print("Calculadora de factoriales")
print("==========================\n")

a = 1
b = int(input("Ingrese un número: "))

while b < 0:
    print("El número ingresado debe ser mayor o igual a 0.")
    b = int(input("Ingrese un número: "))

np_rango = np.arange(a,b+1, step = 1)

suma = 1

for num in np_rango:
    suma *= num
print("\nEl factor del numero ingresado es =",suma)

Calculadora de factoriales

Ingrese un número: 7

El factor del numero ingresado es = 5040


### Desafío 02
- Escribir una función para calcular la suma de una serie comenzando por un número cualquiera y terminando en otro número que debe ser mayor al primero

In [30]:
print("Calculadora de series")
print("=====================\n")

a = int(input("Ingrese un valor 'a': ")) 
b = int(input("Ingrese un valor 'b': "))

while b <= a:
    print("'b' debe ser mayor que 'a'")
    b = int(input("Ingrese un valor 'b': "))

np_rango = np.arange(a,b+1, step = 1)
print("\nLa suma de la serie es =",np_rango.sum())

Calculadora de series

Ingrese un valor 'a': 7
Ingrese un valor 'b': 2
'b' debe ser mayor que 'a'
Ingrese un valor 'b': 3
'b' debe ser mayor que 'a'
Ingrese un valor 'b': 4
'b' debe ser mayor que 'a'
Ingrese un valor 'b': 5
'b' debe ser mayor que 'a'
Ingrese un valor 'b': 6
'b' debe ser mayor que 'a'
Ingrese un valor 'b': 7
'b' debe ser mayor que 'a'
Ingrese un valor 'b': 123

La suma de la serie es = 7605


## Ejercicio 03
En este link se provee un archivo con los resultados de la Encuesta de Sueldos de Openqube de Febrero 2020 (https://sueldos.openqube.io/encuesta-sueldos-2020.02/ ), Calcular y comparar media y mediana de los sueldos netos.

In [24]:
sueldosNetos = np.genfromtxt('Desafio2.csv',dtype = 'int', delimiter = ',', usecols = (5), skip_header = 1, filling_values = 0)

media = round(np.mean(sueldosNetos),1)

mediana = np.median(sueldosNetos)

print("La 'media' de los sueldos netos es =",media)
print("La 'mediana' de los sueldos netos es =",mediana)

diferencia = media - mediana

print("La diferencia entre la 'media'-'mediana' es =",diferencia)

La 'media' de los sueldos netos es = 19047028.7
La 'mediana' de los sueldos netos es = 78000.0
La diferencia entre la 'media'-'mediana' es = 18969028.7
