# Alumno 
Pérez Gastón

## Ejercicio 01
Generar un array aleatorio de 100 elementos. Calcular la mediana correspondiente.

In [4]:
#Importamos librería NumPy

import numpy as np

In [14]:
def arrayRandom ():
    print("\nGenerador de arrays aleatorio compuestos por 100 elementos")
    print("==========================================================")

    arrayAleatorio = np.random.randint(100, size=(10,10))
    
    print("\nSu array Random es:")
    print("-------------------")
    print(arrayAleatorio)
    
    mediana = np.median(arrayAleatorio)
    print("\nLa mediana de su array es =",mediana)

print("Bienvenidx a este programa")
init = int(input("Para comenzar ingrese 1. Si no desea continuar, pulse 0: "))

if init == 1:
    arrayRandom()
else:
    print("La próxima será :)")

consulta = input("¿Quiere volver a utilizar el programa? Responde 'si' para continuar o 'no' para salir: ")

while consulta == "si" or consulta == "SI" or consulta == "Si" or consulta == "sí" or consulta == "SÍ" or consulta == "Sí" or consulta == "sI" or consulta == "sÍ":
    arrayRandom()
    consulta = input("¿Quiere volver a utilizar el programa? Responde 'si' para continuar o 'no' para salir: ")
else:
    print("\n¡Adiós Vaquerx!")

Bienvenidx a este programa
Para comenzar ingrese 1. Si no desea continuar, pulse 0: 1

Generador de arrays aleatorio compuestos por 100 elementos

Su array Random es:
-------------------
[[28 44 59 92 71 41 18 80 19 46]
 [ 0 51 66 10 52 92 18 50 94 17]
 [75 95 34 73 38 86 94 46 64  4]
 [ 3 81 63 82 64 80 96 16  8 52]
 [51 21  9 80 63 17 36 89 78 85]
 [36 37 45 72 43 98 56 25 27 91]
 [20 78 39 27 95 18 46 11 24 55]
 [ 4 11 48 73 82 15  0 41 34 56]
 [65 28 47  9 72 58  9 65 86 97]
 [87  7 25 81 57 74 49 28 69  2]]

La mediana de su array es = 49.5
¿Quiere volver a utilizar el programa? Responde 'si' para continuar o 'no' para salir: Sí

Generador de arrays aleatorio compuestos por 100 elementos

Su array Random es:
-------------------
[[55 37 18 99 52 36 14  8 34 53]
 [12 76 91 51 66 47 22 47 91 76]
 [67 13 74  2 16 74 33  7 54 18]
 [62 21 39 50 66 29 17 77 61 65]
 [92 95 67 92 66 56 79 89 64 40]
 [30 41 77 13 58 64 64  2 60 10]
 [ 3 21  2 12 61 19 97 80 13 87]
 [72 83 89 23 58 21 89 27 

## Ejercicio 02
Recordar los ejercicios con funciones para cálculo de factorial y suma de serie de la Clase 02. Repetir ambos ejercicios, pero ahora utilizar las nuevas operaciones aprendidas con los ndarrays.

### Desafío 01
- Escribir una función para calcular el factorial de un número cualquiera.

In [16]:
print("Calculadora de factoriales")
print("==========================\n")

a = 1
b = int(input("Ingrese un número: "))

while b < 0:
    print("El número ingresado debe ser mayor o igual a 0.")
    b = int(input("Ingrese un número: "))

np_rango = np.arange(a,b+1, step = 1)

fact = np.prod(np_rango)

print("\nEl factor del numero ingresado es =",fact)

Calculadora de factoriales

Ingrese un número: -1
El número ingresado debe ser mayor o igual a 0.
Ingrese un número: 5

El factor del numero ingresado es = 120


### Desafío 02
- Escribir una función para calcular la suma de una serie comenzando por un número cualquiera y terminando en otro número que debe ser mayor al primero

In [30]:
print("Calculadora de series")
print("=====================\n")

a = int(input("Ingrese un valor 'a': ")) 
b = int(input("Ingrese un valor 'b': "))

while b <= a:
    print("'b' debe ser mayor que 'a'")
    b = int(input("Ingrese un valor 'b': "))

np_rango = np.arange(a,b+1, step = 1)
print("\nLa suma de la serie es =",np_rango.sum())

Calculadora de series

Ingrese un valor 'a': 7
Ingrese un valor 'b': 2
'b' debe ser mayor que 'a'
Ingrese un valor 'b': 3
'b' debe ser mayor que 'a'
Ingrese un valor 'b': 4
'b' debe ser mayor que 'a'
Ingrese un valor 'b': 5
'b' debe ser mayor que 'a'
Ingrese un valor 'b': 6
'b' debe ser mayor que 'a'
Ingrese un valor 'b': 7
'b' debe ser mayor que 'a'
Ingrese un valor 'b': 123

La suma de la serie es = 7605


## Ejercicio 03
En este link se provee un archivo con los resultados de la Encuesta de Sueldos de Openqube de Febrero 2020 (https://sueldos.openqube.io/encuesta-sueldos-2020.02/ ), Calcular y comparar media y mediana de los sueldos netos.

In [24]:
sueldosNetos = np.genfromtxt('Desafio2.csv',dtype = 'int', delimiter = ',', usecols = (5), skip_header = 1, filling_values = 0)

media = round(np.mean(sueldosNetos),1)

mediana = np.median(sueldosNetos)

print("La 'media' de los sueldos netos es =",media)
print("La 'mediana' de los sueldos netos es =",mediana)

diferencia = media - mediana

print("La diferencia entre la 'media'-'mediana' es =",diferencia)

La 'media' de los sueldos netos es = 19047028.7
La 'mediana' de los sueldos netos es = 78000.0
La diferencia entre la 'media'-'mediana' es = 18969028.7
