# Alumno 
Pérez Gastón

## Ejercicio 01
Generar un array aleatorio de 100 elementos. Calcular la mediana correspondiente.

In [1]:
#Importamos librería NumPy

import numpy as np

In [25]:
def arrayRandom ():
    print("Generador de arrays aleatorio compuestos por 100 elementos")
    print("==========================================================")

    arrayAleatorio = np.random.randint(100, size=(10,10))
    
    print("\nSu array Random es:")
    print("-------------------")
    print(arrayAleatorio)
    
    mediana = np.median(arrayAleatorio)
    print("\nLa mediana de su array es =",mediana)
    
arrayRandom()

Generador de arrays aleatorio compuestos por 100 elementos

Su array Random es:
-------------------
[[50 44 75 54 85 15 63 31  8 60]
 [73 21 76 45 57 62 45 40 85 59]
 [87 94 41 99 10 11 66 31 81  0]
 [10 71 66 97 24 21 24 88 16 20]
 [71 95 95 73  1  9 43 13 23 56]
 [25  2 37 89 46 13 55 78 65 54]
 [67  0 22 38 33 97  3 20 70 36]
 [21 13 52 26 71  9 59 39 22 68]
 [24 57 28 53 53 33 94 28  2 15]
 [82 31  3 92 81 12 30 77 11 82]]

La mediana de su array es = 44.5


## Ejercicio 02
Recordar los ejercicios con funciones para cálculo de factorial y suma de serie de la Clase 02. Repetir ambos ejercicios, pero ahora utilizar las nuevas operaciones aprendidas con los ndarrays.

In [26]:
def factoriales ():
    
    

SyntaxError: invalid syntax (<ipython-input-26-450703f2e727>, line 1)

## Ejercicio 03
En este link se provee un archivo con los resultados de la Encuesta de Sueldos de Openqube de Febrero 2020 (https://sueldos.openqube.io/encuesta-sueldos-2020.02/ ), Calcular y comparar media y mediana de los sueldos netos.